# Generated by Django 2.0.4 on 2018-04-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='url',
        ),
        migrations.AddField(
            model_name='file',
            name='file_path',
            field=models.FileField(default='test', max_length=300, upload_to=''),
            preserve_default=False,
        ),
    ]
