# Generated by Django 2.0.4 on 2018-08-11 11:06

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_store', '0002_auto_20180414_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/var/local/liftoff'), upload_to=''),
        ),
    ]
