# Generated by Django 2.0.4 on 2018-08-11 17:32

import django.core.files.storage
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('file_store', '0005_auto_20180811_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_path',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='/var/local/liftoff'), upload_to=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
